# Import secrets from local .env file
spring.config.import=optional:file:.env[.properties]

spring.application.name=expensetracker-mvp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Session configuration
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true

# JWT Configuration
app.jwt.access-token-secret=${JWT_ACCESS_SECRET}
app.jwt.refresh-token-secret=${JWT_REFRESH_SECRET}
app.jwt.access-token-expiration-minutes=30
app.jwt.refresh-token-expiration-days=7

# Frontend Configuration
app.frontend.url=${FRONTEND_URL}